# build stage
FROM golang:alpine AS build-env
RUN apk --no-cache add build-base git mercurial gcc
ADD . /src
RUN cd /src && go build -ldflags '-w -s' -a -o pokemon-api

# final stage
FROM alpine
WORKDIR /app
COPY --from=build-env /src/pokemon-api /app/
EXPOSE 8080
ENTRYPOINT ./pokemon-api