apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-api-deployment
  namespace: pokemon-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokemon-api
  template:
    metadata:
      labels:
        app: pokemon-api
    spec:
      containers:
        - name: pokemon-api
          image: andrealmar/pokemon-api:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 400m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 150Mi