apiVersion: v1
kind: Service
metadata:
  name: pokemon-api-service
  namespace: pokemon-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pokemon-api
